spring.application.name=EmployeeJWTJPA
server.port=8080

spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# noinspection SpringProperties
jwt.secret=mysecretkeymysecretkeymysecretkey